feat: add support for Terraform v0.15
mineiros-io/terraform-aws-s3-bucket pull request #46
Opened 2021-05-18 22:48 UTC by soerenmartius

2021-05-19 19:27 UTC, mariux requested changes

2021-05-20 08:36 UTC, soerenmartius commented on README.md
> +[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20and%200.12.20+-623CE4.svg?logo=terraform
nope, doesn't look appropriate to me - there  is absolutely no value in listing every single version. We should use a semver range instead. Also, a badge shouldn't      block the PR.

2021-05-20 08:36 UTC, soerenmartius commented on README.md
> +[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20and%200.12.20+-623CE4.svg?logo=terraform
nope, doesn't look appropriate to me - there  is absolutely no value in listing every single version. We should use a semver range instead. Also, a badge shouldn't      block the PR.

2021-05-20 22:29 UTC, mariux requested changes

2021-05-20 22:29 UTC, mariux commented on README.md
> +j3bffd30e8bdbbde32c143e2650b2faa55f1df3ea/mineiros-primary-logo.svg" width="400"/>][homepage]
thi sbreaks the image

2021-05-20 22:29 UTC, mariux commented on README.md
> +[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20and%200.12.20+-623CE4.svg?logo=terraform
also fine using semver but again 0.15 AND 0.12 is wrong. as it excludes 0.14 and 0.13

2021-05-20 22:29 UTC, mariux commented on README.md
> +[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20and%200.12.20+-623CE4.svg?logo=terraform
```suggestion
[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20|0.14%20|%200.13%20|%200.12.20+-623CE4.svg?logo=terraform
```

2021-05-22 05:53 UTC, soerenmartius commented on README.md
> +j3bffd30e8bdbbde32c143e2650b2faa55f1df3ea/mineiros-primary-logo.svg" width="400"/>][homepage]
resolved in 53f93dc

2021-05-22 05:53 UTC, soerenmartius commented on README.md
> +[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20and%200.12.20+-623CE4.svg?logo=terraform
resolved in 53f93dc

2021-05-22 06:43 UTC, soerenmartius commented on README.md
> +[badge-terraform]: https://img.shields.io/badge/terraform-0.15%20and%200.12.20+-623CE4.svg?logo=terraform
resolved

2021-05-22 14:12 UTC, mariux approved these changes
lgtm

2021-05-23 07:57 UTC, merged